
export enum Template {
  NORMAL = "NORMAL",
  EFFECT = "EFFECT",
  RITUAL = "RITUAL",
  FUSION = "FUSION",
  SYNCHRO = "SYNCHRO",
  DARK_SYNCHRO = "DARK SYNCHRO",
  XYZ = "XYZ",
  LINK = "LINK",
  SPELL = "SPELL",
  TRAP = "TRAP",
  SKILL = "SKILL",
  TOKEN = "TOKEN",
}